version: '3.7'

services:

  react:
    container_name: react
    build:
      context: ./react
      dockerfile: Dockerfile
    env_file:
        - '.env'
    volumes:
      - ./react/public:/app/public
      - ./react/src:/app/src
      - /app/node_modules
    ports:
      - 3001:3000
    environment:
      - CHOKIDAR_USEPOLLING=true
    stdin_open: true
    command: npm start